version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: chat
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    container_name: chat-backend
    ports:
      - '4500:4500'
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/chat
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
    depends_on:
      - postgres
      - redis
    command: pm2-runtime start pm2.config.js --env production
    restart: always

  frontend:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    container_name: chat-frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

volumes:
  pgdata:
